version: '3.3'

services:
    producer:
        image: ndn-producer
        environment:
            CONSUMER: consumer_1        
        build:
            context: ./ndn_doi
            dockerfile: Dockerfile_producer
        deploy:
            restart_policy:
                condition: none              
            
    consumer:
        image: ndn-consumer
        environment:
            PRODUCER: producer
        depends_on:
            - producer
        command: bash -c "screen -dm -L sh -c 'nfd' && sleep 3 && nfdc face create udp://producer &> /dev/null && nfdc route add /example udp://producer &> /dev/null && ./run.sh"
        build:
            context: ./ndn_doi
            dockerfile: Dockerfile_consumer
        deploy:
            restart_policy:
                condition: none



